### ISSUE TITLE
I would like an option to not overwrite Divination

### ISSUE THREAD

**Issue by SuperLargeEggplant** [aiczk/Astro#1]
This is machine-translated English.
Sorry if it doesn't make sense.

If the Divination recast is up, I do not want to automatically play and redraw cards.
I am very afraid that Divination as well as heal abilities etc. will be converted to play and redraw.
Is it possible to create a stop option for such cases?

**Comment by aiczk** [comment]
Hi. 
I'll create an option to not auto-draw/redraw if the ability(s) you set in Config are executable.
Thanks for the suggestion!

**Comment by aiczk** [comment]
Implementation completed in 0.0.0.14.
