### ISSUE TITLE
[Suggestion] Identifiable 60 second bursts

### ISSUE THREAD

**Issue by Nitrodroki** [aiczk/Astro#10]
Since I'm dedicated to making your life hard I'll keep the suggestions coming :p

Checkbox with 'Prioritize identifiable 60 seconds mini-bursts outside of divination window'
Example : 
Phoenix buff on SMN, trick attack on target for NIN, Shroud for RPR, Inner release for warrior, Life of the Dragon for DRG, things like that.

**Comment by aiczk** [comment]
Thanks for the Issue.
OK, it may take some time, but I will try to implement it.

**Comment by aiczk** [comment]
I think I would like to implement the "priority for 60-second burst" as an alternative to the idea you suggested.
I'm thinking of tying it to the "Deal three cards at burst" option, and then play the overflow cards in the order of priority above.

**Comment by aiczk** [comment]
Maybe the method I suggested can be implemented without causing too many bugs.
Maybe.

**Comment by aiczk** [comment]
This feature was implemented in ver 1.22.

**Comment by Nitrodroki** [comment]
I'm testing it tonight
