### ISSUE TITLE
Not respecting divination window.

### ISSUE THREAD

**Issue by Impurities** [aiczk/Astro#11]
Hey, I wanted to report that astro's divination functionality seems to be inversed, as it auto plays outside of divination windows, and doesn't play during divination windows.

I'd also like to mention that you can no longer manually play, as it'll only target yourself.

**Comment by Nitrodroki** [comment]
I've not had this problem, what checkbox are you using ? Mindsharing a screen of your settings ?

**Comment by Impurities** [comment]
![image](https://user-images.githubusercontent.com/23531970/175470607-8e7e230c-dc63-44b1-9353-e22e1b37cac0.png)

Here are my settings, I've reinstalled the plugin various times with no way to fix it yet.

**Comment by Nitrodroki** [comment]
Checked my footage and saw no problem with it but I don't use any auto feature. @aiczk Is it possible some new features broke some auto-features ?

EDIT : I've had range cards prioritize melees during divination window very weirdly, there might be some kinks yet.

**Oh yes, after careful examination. Divination window seems to consider ranged cards as melee cards**

**Comment by aiczk** [comment]
It looks like I reversed the conditional statement when implementing the new feature in ver 1.12.
Sorry about that. I will fix it right away.

**Comment by aiczk** [comment]
I just released ver 1.14.
I think this problem has been fixed.
so sorry.

**Comment by Impurities** [comment]
Confirmed fixed!! Thank you both! Also, is it possible to make it so that it can manually assign cards out of combat? It used to be able to do so, but it is no longer possible ever since the new update.

**Comment by Nitrodroki** [comment]
I believe th plugin fundamentally change the function of the play button, there might be a need for additionnal checkbox to activate freedom outside of combat

**Comment by aiczk** [comment]
Yes, a new option is needed.
We will implement it in the next update. Thanks for the good ideas.

**Comment by Nitrodroki** [comment]
I believe a macro to toggle the plugin should also be implemented, so that you can basically use an ingame macro to play vanilla whenever you prefer it.
Something like /astro off

**Comment by Impurities** [comment]
Also, auto play with "Deal three cards at burst" option are bugged, as it keeps assigning cards to myself instead of my teammates. Manual input works though, but only during combat, as does auto play work without the 3 burst option enabled.

**Comment by aiczk** [comment]
The on, off, and toggle commands have been implemented in ver1.15.
Many options were also added.
 A bug in the "Deal three cards at burst" option is under investigation.

Sorry if there is a bug...;;

**Comment by aiczk** [comment]
Sorry, it's buggy, I'll fix it now...

**Comment by Impurities** [comment]
Hey, it seems like astro auto play/auto re-draw doesn't work at all, with or without Deal three cards at burst window option.
Drawing cards manually doesn't work out of combat either, but that isn't important if it's too much to ask :)
Also, Toggle on and off are inverted, off seems to turn it back on, and on seems to turn it off.

Thank you for the amazing plugin <3

**Comment by aiczk** [comment]
Fixed a bug in ver1.17 that on and off were reversed.
Sorry for the delay.

If you are manually selecting targets and dealing cards, try turning off the "Enable Manual Play" option.

**Comment by Impurities** [comment]
Thanks for the bug fix! Auto play/re-draw still isn't working on my end, tried with only Enable Auto Play and Toggle status, it is still not automatically playing cards to party members.

I'm sorry if I'm not being clear enough, when manually pressing "play" out of combat, it will only assign cards to myself, instead of party members.

**Comment by aiczk** [comment]
The issue of the automatic play not working is currently being investigated.
We apologize for the inconvenience, but please be patient. ;;

**Comment by Impurities** [comment]
That's okay!! Thank you for your hard work <3

**Comment by aiczk** [comment]
I was able to fix it in ver 1.19.
Maybe all the features should work correctly.

**Comment by Impurities** [comment]
Thank you for the update!

Scratch that, it's not crashing, but auto play is not working.

EDIT: never mind, everything seems to be working just fine. Will continue to use, will report back after raiding.

EDIT 3: Okay, I am terribly sorry, it seems to be a hit or miss so far, sometimes it works and sometimes it doesn't, I've been testing it with a friend in explorer mode and it started working just fine, but after the first divination burst, it stopped working entirely, overcapped on cards and it is not auto playing when under divination, or when out of divination, it seems to stop working entirely after autoredraw happens, I can 100% replicate, and fix by uninstalling and reinstalling the plugin.

**Comment by aiczk** [comment]
I believe the problem has been resolved in ver 1.20.
Thank you for verifying the behavior and reporting the details.
I apologize for the inconvenience.

**Comment by Impurities** [comment]
Everything seems to be working as intended, thank you! Closing issue <3
