### ISSUE TITLE
Cards not being delivered to priority order.

### ISSUE THREAD

**Issue by DatGoose** [aiczk/Astro#14]
Starting out; the plugin will function as expected and throw cards to the intended targets in their order
I've adjusted the order to include WAR and GNB for my DSR group, the range cards have not been changed.

After two or three pulls the priority order is completely ignored. The SAM wont get any cards unless triple melee is pulled, and top priority is SMN for my group yet all cards flow to DNC and RDM.

I'm not sure if there is anything I could provide on

**Comment by aiczk** [comment]
Thanks for the Issue.
I will check it.
