### ISSUE TITLE
Update for 6.2 

### ISSUE THREAD

**Issue by BobBongo** [aiczk/Astro#16]
Hi,

Wondering if this plugin will be updated for 6.2?

Thank you

**Comment by it-erativo** [comment]
I'd like to know too! I hope it is, it's one of my favorite plugins since I found it in 6.1.

Thank you very much ^-^

**Comment by aiczk** [comment]
Since I have been away from FFXIV for a long time, it takes time to update, but let's do it.

**Comment by aiczk** [comment]
Oh, I don't know what to do, so I can't do maintenance.
I'm sorry.
