### ISSUE TITLE
automatic selection of card targets when playing manually

### ISSUE THREAD

**Issue by SuperLargeEggplant** [aiczk/Astro#2]
I would like to see automatic selection of card targets when cards are played manually when the automatic execution of card Play and Redraw is stopped due to Divination, etc.
I play with a controller and sometimes I want to Play manually, but then it is very difficult to target an ally.
Thanks for all your help.

**Comment by aiczk** [comment]
Sorry for the delay in noticing.
Got it! Your proposal is very good, so we will implement it as a specification.
I have to go out today, so I will do my best to update it between tonight and tomorrow.

**Comment by aiczk** [comment]
sry, The release will be delayed due to a prolonged schedule.
I'll update it tomorrow, so please wait.

**Comment by aiczk** [comment]
Implementation completed in 0.0.1.0.
