### ISSUE TITLE
Crash when pressing Play while no card is drawn.

### ISSUE THREAD

**Issue by Impurities** [aiczk/Astro#5]
I'm not sure if this is an isolated issue but, when having the plugin installed, pressing play when no cards are drawn will crash the game, this makes other plugins like xivcombo impossible to use with Draw/Play feature, as it makes Astro plugin play with no cards drawn, which makes the game crash.

**Comment by aiczk** [comment]
Thanks for the Issue.
Maybe that issue was resolved in Issue [#3](https://github.com/aiczk/Astro/issues/3). 
I'll put in the combo tool and give it a try just to be sure.
