### ISSUE TITLE
Question about job priority

### ISSUE THREAD

**Issue by voss89** [aiczk/Astro#6]
Hello, amazing work with this plugin, I love it

Just a question, is it possible to add an option to change the job priority list?

**Comment by aiczk** [comment]
Thanks for the issue.
OK, we will make it happen! I'll probably have it ready for release by the end of the day.

**Comment by aiczk** [comment]
Thanks for the great idea!
Implemented in ver1.7 to specify the priority to distribute cards!
I'd like to believe there's probably no bug, but let me know if there is! 
I'll fix it right away.
