### ISSUE TITLE
Request : Consider cards as 'in burst' when Divination has less than X seconds before its ready.

### ISSUE THREAD

**Issue by Nitrodroki** [aiczk/Astro#8]
An additionnal request, sorry for bombarding them would be to have a checkbox of 'Consider cards as 'In burst' while divination CD is about to be available/is available' behavior.

The idea is to be able to use the 2 first cards before divination in the opener and reopener on burst targets eventho divination has not been used yet.

https://media.discordapp.net/attachments/583963017746579477/938881667253293126/ast_ew_opener_4.png?width=663&height=671

Basically a 'Treat cards as in burst while divination is close to being ready' option.

**Comment by aiczk** [comment]
Thanks for the Issue. That's a great idea.
OK, I will try to see if I can implement it.

**Comment by aiczk** [comment]
Implemented in ver 1.11.
We think we were probably able to implement it as you requested.
Sorry if it was different.

**Comment by Nitrodroki** [comment]
Looking at code, it seems like it's there but my astro in 0.1.12 is not showing the option for the EnableBurstCard variable
https://i.imgur.com/y9APJjO.png

Is it activated by default, or baked in another checkbox ?

**Comment by aiczk** [comment]
The "EnableBurstCard" checkbox is the "Deal three cards at burst" checkbox, so I think it is shown in the image.

As for the "Treat cards as in burst while divination is close to being ready" checkbox, I had to turn on the "Deal three cards at burst" option to make it appear.

https://github.com/aiczk/Astro/blob/main/Astro/Ui.cs#L42

I apologize. We will fix it immediately.

**Comment by aiczk** [comment]
Maybe ver 1.13 could fix it.

**Comment by Nitrodroki** [comment]
It seems to work, but hard to actually test in real condition without screwing my party. But so far so good.

**Comment by aiczk** [comment]
I'll be thinking about this issue.
If i find a better way to implement it, i'll fix it again. Thanks.
