### ISSUE TITLE
Suggestion : Use redraw when pressing play if seal is redundant and redraw is available

### ISSUE THREAD

**Issue by Nitrodroki** [aiczk/Astro#9]
Don't even know if it's possible.

For those who don't use the auto play/redraw, you could have the option to redraw when pressing the play button and the seal is redundant if redraw is available, basiically the same as the auto function but with manual presses.

Generally the auto function is inserting ogcd that cause clipping and dangerous situations in hard content like ultimates if some important healing ogcd doesnt fire so the basic improving of the 'play' behavior is gonna be most of my suggestions ;)

Would basically allow spamming of the play button without thinking and having the plugin resolve the redraw and the priority target.

**Comment by Nitrodroki** [comment]
Asked for the feature in XIV combo expanded in case its a more fitting feature since they have comparable behavior for some combos https://github.com/daemitus/XIVComboPlugin/issues/181

**Comment by aiczk** [comment]
The functionality has been separated from the Auto Redraw option and is newly implemented in ver 1.11.

**Comment by Nitrodroki** [comment]
Hmmm, checking the box uses redraw as an inserted action after draw if seal is redundant. Is it a bug ?
Wanted the play button to execute redraw instead of play if seal is redundant, maybe I miscommicated ? I don't quite see the difference between auto redraw and enable manual redraw in their current implementation

**Comment by aiczk** [comment]
With the option ON, when you run Play (e.g. The Balance), if Seal is verbose, it will be converted to Redraw.

I'm going to work now, so I can't fix it right away, but I'll think about how to implement it, sorry.

**Comment by Nitrodroki** [comment]
You don't have to apologize :)

**Comment by aiczk** [comment]
I checked the behavior and it still converts "play" to "redraw" if the seal is redundant.
Do you mean you want the icon to be "redraw"?

**Comment by Nitrodroki** [comment]
I'll check again, last time i tried it, it just inserted redraw after draw as extra ogcd instead of what i wanted which was to replace play with redraw when pressing play and seal redundant. I'll come back to you later.

**Comment by Nitrodroki** [comment]
Perfect, Tested and it's exactly what i asked for :) You are pog

**Comment by aiczk** [comment]
Thank you. Glad I could provide you with something appropriate.
